const axios = require('axios');

// Forward user image payload directly to FastAPI engine
exports.processAIInference = async (req, res) => {
    try {
        const { image_payload } = req.body;

        if (!image_payload) {
            return res.status(400).json({ error: 'AI processing failed. Image payload string missing.' });
        }

        // Trigger request to local Python FastAPI Microservice endpoint
        const aiResponse = await axios.post('http://127.0.0.1:8000/ai/predict', {
            image_payload: image_payload
        });

        // Return the analytical matrix generated by Python back to client
        return res.status(200).json({
            message: 'Pipeline data exchange completed successfully.',
            ai_engine_output: aiResponse.data
        });

    } catch (err) {
        return res.status(500).json({ 
            error: 'Cross-server handshake failed during AI pipeline execution.', 
            details: err.message 
        });
    }
};